name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Устанавливаем необходимые зависимости
      - name: Install dependencies
        run: sudo apt-get install -y lcov

      # Запускаем cmake, указывая исходники в 05_hw
      - name: Configure CMake
        run: cmake -S 05_hw -B build -DENABLE_SANITIZERS=ON -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: |
          cd build
          ctest --verbose

        - name: Coverage Report
        run: |
          lcov --capture --directory build --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info || true
          genhtml coverage.info --output-directory coverage
        

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage
